linters:
  enable:
    - errcheck
    - staticcheck
    - govet
    - ineffassign
    - unused

issues:
  exclude-rules:
    # Ignore unchecked errors in defer statements
    - text: "Error return value of.*defer"
      linters:
        - errcheck
    
    # Ignore specific staticcheck issues in tests
    - path: _test\.go
      linters:
        - staticcheck
      text: "(SA5011|SA9003|SA4031)"
    
    # Ignore registry nil context
    - path: internal/providers/registry\.go
      linters:
        - staticcheck
      text: "SA1012"

run:
  timeout: 5m
